name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2
      
      - name: Install dependencies
      - run: |
          apt update
          apt install clang make pkg-config libgtk-4-dev libluajit-5.1-dev
      
      - name: Build
      - run: CC=clang CXX=clang++ make all
      
      - name: Upload executable
      - uses: actions/upload-artifact@v2
        with:
          name: csa-linux
      
      - name: Upload test executable
      - uses: actions/upload-artifact@v2
        with:
          name: csa-testbench-linux
          path: testbench

  test-linux:
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2
      
      - name: Install dependencies
      - run: |
          apt update
          apt install libgtk-4-dev libluajit-5.1-dev
      
      - name: Download test executable
      - uses: actions/download-artifact@v2
        with:
          name: csa-testbench-linux
      
      - name: Run tests
      - run: ./testbench
  
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2
      
      - name: Install dependencies
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install gtk4 luajit
            
      - name: Build
      - run: CC=clang CXX=clang++ make all
      
      - name: Upload executable
      - uses: actions/upload-artifact@v2
        with:
          name: csa-macos
          path: Captain Sonar Assist.app
      
      - name: Upload test executable
      - uses: actions/upload-artifact@v2
        with:
          name: csa-testbench-macos
          path: testbench

  test-macos:
    runs-on: macos-latest
    needs: build-macos
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2
      
      - name: Install dependencies
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install gtk4 luajit
      
      - name: Download test executable
      - uses: actions/download-artifact@v2
        with:
          name: csa-testbench-macos
      
      - name: Run tests
      - run: ./testbench
  
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2
      
      - name: Install MSYS2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-gtk4
            mingw-w64-x86_64-luajit
            
      - name: Build
      - run: CC=clang CXX=clang++ mingw32-make all
      
      - name: Upload executable
      - uses: actions/upload-artifact@v2
        with:
          name: csa-windows
          path: csa.exe
      
      - name: Upload test executable
      - uses: actions/upload-artifact@v2
        with:
          name: csa-testbench-windows
          path: testbench.exe

  test-windows:
    runs-on: windows-latest
    needs: build-windows
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2
      
      - name: Install MSYS2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            mingw-w64-x86_64-gtk4
            mingw-w64-x86_64-luajit
      
      - name: Download test executable
      - uses: actions/download-artifact@v2
        with:
          name: csa-testbench-windows
      
      - name: Run tests
      - run: ./testbench
